server: 
    port: 3015
logging:
    level: 
        org.springframework: info
        data: DEBUG
        security: DEBUG
    config: classpath:logback-spring.xml
spring:
    datasource:
        db1:
#            driverClassName: com.mysql.cj.jdbc.Driver
#            username: liby
#            password: A*bing@_2019
#            jdbcUrl: jdbc:mysql://47.98.57.221:3306/penguin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#            type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.mysql.jdbc.Driver
          username: root
          #password: 123456
          password: 115bcdf569d247c3
          jdbcUrl: jdbc:mysql://192.168.10.165:3306/penguin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
          #jdbcUrl: jdbc:mysql://192.168.10.165:3307/penguin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
          type: com.alibaba.druid.pool.DruidDataSource

        db2:
            driver-class-name: com.mysql.jdbc.Driver
            username: root
              #password: 123456
            password: 115bcdf569d247c3
            jdbcUrl: jdbc:mysql://192.168.10.165:3306/penguin?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
            type: com.alibaba.druid.pool.DruidDataSource


    druid:
       # 下面为连接池的补充设置，应用到上面所有数据源中
       # 初始化大小，最小，最大
       initial-size: 2
       min-idle: 3
       max-active: 20
       # 配置获取连接等待超时的时间
       max-wait: 60000
       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       time-between-eviction-runs-millis: 60000
       # 配置一个连接在池中最小生存的时间，单位是毫秒
       min-evictable-idle-time-millis: 300000
       #用来检测连接是否有效的sql 必须是一个查询语句
       #mysql中为 select 'x'
       #oracle中为 select 1 from dual
       validation-query: select 'x'
       #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
       test-while-idle: true
       #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
       test-on-borrow: false
       #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
       test-on-return: false
       #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false  配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
       pool-prepared-statements: false
       max-pool-prepared-statement-per-connection-size: 20
       filters: stat,wall
       use-global-data-source-stat: true
       # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
       connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     # 配置监控服务器
       stat-view-servlet:
           login-username: admin
           login-password: admin
           #页面数据重置 false 就是无法重置
           reset-enable: false
           url-pattern: /druid/*
           # 添加IP白名单
           #allow: 127.0.0.1,192.168.163.1
           # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
           #deny: 192.168.1.73
       web-stat-filter:
           # 添加过滤规则
           url-pattern: /*
           # 忽略过滤格式
           exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
    mvc:
        static-path-pattern: /**
    thymeleaf:
      servlet:
          content-type: text/html
      encoding: UTF-8
      cache: false

swagger:
    enabled: true

mybatis:
    typeAliasesPackage: com.penguin.website.model
    configuration:
        map-underscore-to-camel-case: true

pagehelper: 
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

#上传目录
imageUrl: d:/code/sk/website/
#imageUrl: /data
#映射目录
imageUrlYS: /root/abc/
#imageUrlYS: /data/upload/

## 订单失效时间用户30分钟，商户1小时
order:
  overtime:
    user: 30
    merchant: 60
    sell:
      user: 2

penguin:
  appId: 15c6b70fc0db
  appSecret: 7b94177c40ef4f70b594a287e9cec727
  url:
    userData: http://39.108.110.118:12321/external/user_data
    userTrade: http://39.108.110.118:12321/external/trade
    merchant:  http://39.108.110.118:12321/external/merchants
    vueHost: http://192.168.10.110:8080
    sendOtp: http://120.25.106.59:81/member/game/sendOtpForResetFund
    checkSendOtp: http://120.25.106.59:81/member/game/checkSendOtpForResetFund
  limit:
    sell:
      max: 10000
      min: 742
    recharge:
      max: 30